### ISSUE TITLE
User Story 1: To understand the purpose of the site at a glance

### ISSUE THREAD

**Issue by PrajaktaSarnaik** [PrajaktaSarnaik/mind-matters-project#1]
User Story : 
As a website visitor, I want to understand the purpose of the site at a glance, so that I can decide if the website meets my needs for mental health resources and support.

**Acceptance Criteria**

- [x] The homepage displays a clear and concise headline about mental health awareness.
- [x] Features a welcoming design with calming visuals.
- [x] A navigation menu is accessible at the top of the page.
- [x] Includes an "Emergency" button showing helpline number for emergencies.
- [x] Includes Myths and Facts about mental health.
- [x] Includes mental health problems and their solutions.
- [x] A dedicated section displays testimonials with user quotes, names (optional) and a profile picture/avatar (if provided).
- [x] Includes a section for frequently asked questions (FAQs) about mental health.

**Tasks**

- [x] Create a section with a headline and subheadline.
- [x] Design a navigation menu with links to all key sections (Awareness, Support, Resources, Contact).
- [x] Include images or video that evokes trust and calmness.
- [x] Add a prominent "Emergency" button.
- [x] Add carousel with image and Myths and Facts information.
- [x] Add flip cards to tell about mental health problems and solutions.
- [x] Design a testimonials section with user quotes, optional profile pictures, and attribution.
- [x] Write and design an FAQ section addressing common concerns about Mental health.
