### ISSUE TITLE
User Story 2:  Information about support groups, therapy options, and peer networks.

### ISSUE THREAD

**Issue by PrajaktaSarnaik** [PrajaktaSarnaik/mind-matters-project#2]
User Story : As a user in need of ongoing support, I want to find information about support groups, therapy options, and peer networks, so that I can connect with others and access personalized help.

**Acceptance Criteria**

- [x] The support page lists various support options, including group sessions, one-on-one sessions and online communities.
- [x] Each option provides a brief description and a link to join or learn more.
- [x] Includes a section for frequently asked questions (FAQs) about mental health.

**Tasks**

- [x] Make a provision to book for support groups, one-on-one sessions and online session.
- [x] Ensure content accessibility for screen readers and mobile devices.
