### ISSUE TITLE
User Story 3: A list of reliable resources.

### ISSUE THREAD

**Issue by PrajaktaSarnaik** [PrajaktaSarnaik/mind-matters-project#3]
User Story :  As a user seeking mental health support, I want to find a list of reliable resources, so that I can access professional help or self-help guides.

**Acceptance Criteria**

- [x] A list of resources (e.g., Helplines, Articles or Videos) is displayed.
- [x] Each resource has a brief description and link to learn more.
- [x] Resource content is easy to accessible on mobile devices.

**Tasks**

- [x] Research and compile a list of trusted mental health videos.
- [x] Test responsiveness for mobile and tablet devices.
