### ISSUE TITLE
User Story 4: Contact information for the website team or access to urgent helpline number.

### ISSUE THREAD

**Issue by PrajaktaSarnaik** [PrajaktaSarnaik/mind-matters-project#4]
User Story : As a user in need of guidance, I want to contact the website team or access urgent helpline numbers, so that I can get help or share feedback about the site.

**Acceptance Criteria**

- [x] The page includes a contact form with fields: Name, Email, Phone Number, Select from option and Message.
- [x] Displays a emergency helpline with contact number.
- [x] The form provides a success message after submission.

**Tasks**

- [x] Design and implement the contact form.
- [x] Add validation for required fields (e.g., email must be in proper format).
- [x] Include an emergency  helpline number.
- [x] Disply a thank you pop up message after a form submission.
